lerror: Portable implementation of glibc's error_at_line()
This addresses issue #4 and will hopefully allow to build against C
libraries other than GNU libc. Provides a portable implementation of
error_at_line() based on strerror() and cpp.

Remains to be tested; expect results sometime next week. If all goes
well, this will replace the LERROR() definition in forecast.h.